(()=>{
let auth,db,me,profile={},users=[],room={id:'public',peer:null,title:'Offentlig chat'},off=null,wired=false;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(m){let e=$('toast');if(!e)return alert(m);e.textContent=m;e.hidden=false;clearTimeout(toast.x);toast.x=setTimeout(()=>e.hidden=true,3500)}
function css(){if($('chatFixCss'))return;let s=document.createElement('style');s.id='chatFixCss';s.textContent='.room-list .room{width:100%;text-align:left}.room-list .room small{display:block;color:var(--muted);margin-top:4px}.messages{display:grid;gap:10px;max-height:58vh;overflow:auto}.msg{display:flex}.msg.me{justify-content:flex-end}.bubble{max-width:82%;padding:11px 13px;border-radius:18px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.075)}.msg.me .bubble{background:rgba(228,184,78,.13);border-color:rgba(228,184,78,.28)}.bubble b{display:block;color:var(--gold);font-size:13px;margin-bottom:5px}.bubble p{margin:0;white-space:pre-wrap;line-height:1.35}.bubble time{display:block;color:var(--muted);font-size:11px;margin-top:6px}.chat-empty{border:1px dashed rgba(228,184,78,.28);border-radius:16px;padding:14px;color:var(--muted);text-align:center}';document.head.appendChild(s)}
function name(u){return u?.name||u?.email?.split('@')[0]||'Spiller'}
function dm(a,b){return 'dm_'+[a,b].sort().join('_')}
function rooms(){let list=document.querySelector('.room-list');if(!list||!me)return;let others=users.filter(u=>u.uid!==me.uid);list.innerHTML='<button class="room '+(room.id==='public'?'active':'')+'" data-public="1"><b>Offentlig chat</b><small>Alle</small></button>'+others.map(u=>'<button class="room '+(room.peer===u.uid?'active':'')+'" data-peer="'+esc(u.uid)+'"><b>'+esc(name(u))+'</b><small>Privat melding</small></button>').join('');list.querySelector('[data-public]')?.addEventListener('click',()=>{room={id:'public',peer:null,title:'Offentlig chat'};open()});list.querySelectorAll('[data-peer]').forEach(b=>b.onclick=()=>{let uid=b.dataset.peer,u=users.find(x=>x.uid===uid);room={id:dm(me.uid,uid),peer:uid,title:'Privat: '+name(u)};open()})}
function open(){if($('roomTitle'))$('roomTitle').textContent=room.title;rooms();listen()}
function listen(){if(off)try{off()}catch{};let box=$('messages');if(box)box.innerHTML='<div class="chat-empty">Laster meldinger...</div>';if(!db||!me)return;off=db.collection('chatMessages').where('room','==',room.id).onSnapshot(s=>{let arr=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.createdAtMs||0)-(b.createdAtMs||0)).slice(-80);if(!box)return;if(!arr.length){box.innerHTML='<div class="chat-empty">Ingen meldinger ennå.</div>';return}box.innerHTML=arr.map(m=>'<div class="msg '+(m.userId===me.uid?'me':'')+'"><div class="bubble"><b>'+esc(m.author||'Spiller')+'</b><p>'+esc(m.text||'')+'</p><time>'+(m.createdAtMs?new Date(m.createdAtMs).toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit'}):'')+'</time></div></div>').join('');box.scrollTop=box.scrollHeight},e=>{console.error(e);if(box)box.innerHTML='<div class="chat-empty">'+esc((e.code?e.code+': ':'')+(e.message||'Chat-feil'))+'</div>'})}
async function send(e){e.preventDefault();let inp=$('chatInput'),txt=(inp?.value||'').trim();if(!txt)return;if(!me)return toast('Logg inn først');try{let data={room:room.id,roomType:room.peer?'dm':'public',userId:me.uid,author:name(profile)||name(me),text:txt,createdAtMs:Date.now(),createdAt:firebase.firestore.FieldValue.serverTimestamp()};if(room.peer)data.members=[me.uid,room.peer].sort();await db.collection('chatMessages').add(data);inp.value='';inp.focus()}catch(x){console.error(x);toast((x.code?x.code+': ':'')+(x.message||'Kunne ikke sende melding'))}}
function wire(){if(wired)return;let f=$('chatForm');if(!f)return;wired=true;f.addEventListener('submit',send)}
function boot(){css();wire();let timer=setInterval(()=>{wire();if($('chatForm'))clearInterval(timer)},300);if(!window.firebase||!window.VM_FIREBASE_CONFIG)return;if(!firebase.apps.length)firebase.initializeApp(window.VM_FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();auth.onAuthStateChanged(async u=>{me=u;if(!u){if($('messages'))$('messages').innerHTML='<div class="chat-empty">Logg inn for å bruke chat.</div>';return}try{let d=await db.collection('users').doc(u.uid).get();profile=d.exists?d.data():{email:u.email}}catch{profile={email:u.email}}db.collection('users').onSnapshot(s=>{users=s.docs.map(d=>({uid:d.id,...d.data()}));rooms();if(!off)listen()},e=>toast((e.code?e.code+': ':'')+'Kunne ikke hente brukere'));room={id:'public',peer:null,title:'Offentlig chat'};open()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
