(()=>{
let db,auth,stop;
const R=[['Rookie',0],['Bronze',900],['Silver',1100],['Gold',1300],['Elite',1600],['Legend',2000]];
function init(){if(!window.firebase||!window.VM_FIREBASE_CONFIG)return false;if(!firebase.apps.length)firebase.initializeApp(window.VM_FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();return true}
function getRank(e){let c=R[0],n=null;for(let i=0;i<R.length;i++){if(e>=R[i][1]){c=R[i];n=R[i+1]||null}}return{c,n}}
function addCss(){if(document.getElementById('profileRankCss'))return;let s=document.createElement('style');s.id='profileRankCss';s.textContent='.profile-rank-card{margin-top:14px;padding:14px;border-radius:22px;background:rgba(8,22,42,.9);border:1px solid rgba(228,184,78,.2)}.profile-rank-card h3{margin:0 0 8px}.profile-rank-elo{font-size:30px;font-weight:1000;color:var(--gold)}.profile-rank-bar{height:12px;border-radius:99px;background:rgba(255,255,255,.08);overflow:hidden;margin:10px 0}.profile-rank-bar i{display:block;height:100%;background:linear-gradient(90deg,#d79b2f,#f2d37a)}.profile-rank-card p{margin:0;color:var(--muted);font-size:12px;font-weight:800}.profile-rank-badges{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.profile-rank-badges span{border:1px solid rgba(255,255,255,.1);border-radius:99px;padding:7px 9px;font-size:12px;font-weight:900}.profile-rank-badges .on{color:var(--gold);background:rgba(228,184,78,.12)}';document.head.appendChild(s)}
function card(){addCss();let c=document.getElementById('profileRankCard');if(c)return c;c=document.createElement('article');c.id='profileRankCard';c.className='profile-rank-card';let p=document.getElementById('page-profile')||document.querySelector('.main');p&&p.appendChild(c);return c}
function render(u){let c=card();if(!c)return;let e=Number(u.gamblingElo||u.elo||1000),r=getRank(e),min=r.c[1],max=r.n?r.n[1]:e,p=r.n?Math.max(0,Math.min(100,Math.round((e-min)/(max-min)*100))):100,w=Number(u.wonBets||0),d=Number(u.completedBets||0);let b=[['Forste seier',w>=1],['5 vinn',w>=5],['10 vinn',w>=10],['25 ferdige spill',d>=25]].map(x=>'<span class="'+(x[1]?'on':'')+'">'+x[0]+'</span>').join('');c.innerHTML='<h3>Gambling rank: '+r.c[0]+'</h3><div class="profile-rank-elo">'+e+' ELO</div><div class="profile-rank-bar"><i style="width:'+p+'%"></i></div><p>'+(r.n?(r.n[1]-e)+' ELO til '+r.n[0]:'Maks rank')+' - vinn gir +25, tap gir -15</p><div class="profile-rank-badges">'+b+'</div>'}
function boot(){if(!init())return;auth.onAuthStateChanged(u=>{if(stop){try{stop()}catch(e){}}if(!u)return;stop=db.collection('users').doc(u.uid).onSnapshot(s=>{if(s.exists)render(s.data())})})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();